version: '3.8'

services:
  mysql_backend_test_java:
    image: mysql:8.1.0
    container_name: backend_test_java_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: backend-test-java
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app_backend_test_java:
    build: .
    container_name: backend_test_java
    ports:
      - "8080:8080"
    depends_on:
      - mysql_backend_test_java

volumes:
  mysql_data:
