spring:
  application:
    name: backend-test-java
  datasource:
    url: jdbc:mysql://mysql_backend_test_java:3306/backend-test-java
    username: admin # ou root se preferir
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate # Evita conflitos com Liquibase
    show-sql: false # Pode ser desativado em produção
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect